jdbcSettings:
  url: jdbc:mysql://127.0.0.1:3306/data_manager?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: twindatapwd

packageName: "com.xlasers.mybatisplus.targets"